### ISSUE TITLE
On comments

### ISSUE THREAD

**Issue by iMerica** [kbilsted/CodeQualityAndReadability#11]
Hi, thanks for putting this together! I agree with lots of the points made in [On the changing notion of code readability](https://github.com/kbilsted/CodeQualityAndReadability/blob/master/Articles/Readability/TheChangingNotionOfReadability.md). I thought I'd point out that using Gists to publish these markdown documents would be a lot better because gists have a built-in comments feature. This repo is probably missing out on lots of feedback and comments because commenting via commits is kinda awkward.

http://gist.github.com

Kind regards,

Michael

**Comment by kbilsted** [comment]
Hi Michael

Thanks for the feedback. I haven't used GISTs all that much. I'll do some spike experiments to get a feeling of it. I do like the fact that everyone are able to directly edit/improve my writings.

**Comment by kbilsted** [comment]
I don't think gists are viable. It is difficult to clone, change and push from local. Or do you have a nice way of working with multiple gists @iMerica  ?

**Comment by kbilsted** [comment]
haven't heard from you and I have not found a solution.
