### ISSUE TITLE
Private User repo on GitPullOrCloneAllFromGithubViaApi.md

### ISSUE THREAD

**Issue by Marcus-James-Adams** [kbilsted/CodeQualityAndReadability#25]
The code works fine with private organisation repos, but if you change it to look at user repo's it only puls down public and not private repos.  I have tried adding &type=private into the uri but it still only returns public.

**Comment by kbilsted** [comment]
Thanks for the feedback. I think GitHub can answer why. They are quick to reply and if you find a solution i am very interested in learning it and update the article
